### ISSUE TITLE
testing a trained network

### ISSUE THREAD

**Issue by Shoebtamboli** [ljanyst/ssd-tensorflow#1]
@ljanyst Hi, i have trained the model on pascal voc. And also i'm trying to test using single image with infer.py but i'm not able to see the image with bounding boxes.
i'm getting like this:

[i] Project name:       test
[i] Training data:      pascal-voc/training-data.pkl
[i] Batch size:         32
[i] Data source:        None
[i] Data directory:     pascal-voc
[i] Output directory:   test-output
[i] Annotate:           False
[i] Dump predictions:   False
[i] Sample:             test
[i] Threshold:          0.5
[i] Pascal summary:     False
[!] No files specified

I am new to tensorflow.. can you tell me where i am wrong or how to test it??

**Comment by Shoebtamboli** [comment]
hey i got it

**Comment by Houliuyu** [comment]
I met the same error,could you please tell me how to address it?

**Comment by Houliuyu** [comment]
@Shoebtamboli I met the same error,could you please tell me how to address it?
