### ISSUE TITLE
exporting model

### ISSUE THREAD

**Issue by PushyamiKaveti** [ljanyst/ssd-tensorflow#10]
I am trying to export the model. I see that I need to give a list of output nodes. I am not completely sure as to what to pass for that argument. some one help please !

**Comment by ljanyst** [comment]
This is the name of the output tensor(s) of the model. Tensorflow walks the graph from this tensor back to the input to determine which variables should be exported. The tool in my repository is meant to be generic and usable for any model, so I did not hardcode anything. What you want here for my implementation of SSD is `result/result`. I will update the docs.
