### ISSUE TITLE
How about your hardware set?

### ISSUE THREAD

**Issue by ndaidong** [ljanyst/ssd-tensorflow#11]
Thank you for sharing your implemenation.

Could you share a little info about your hardware? When I run your code with GeForce GTX 1060 6GB,  it always says "out of memory".

**Comment by ljanyst** [comment]
I have a GeForce GTX 1080 Ti with 11GB. I have made some changes to the implementation that reflect more the original one and will be committing them today. It will be a smaller model than the current one, so it might work for you.

**Comment by ljanyst** [comment]
I have now committed the changes I mentioned in my previous comment. Let me know if they reduce model enough for it to work for you.

**Comment by ndaidong** [comment]
Thank you so much, @ljanyst

**Comment by ndaidong** [comment]
@ljanyst it works for me now. How long has it taken to finish your training? In my system, it takes about 30 minutes for each of epoch. I guess that I have to wait for 3 days to complete :)

**Comment by ljanyst** [comment]
It's about a day for the vgg300 flavor.

**Comment by ndaidong** [comment]
@ljanyst thank you for sharing info.
