### ISSUE TITLE
Training on custom dataset 

### ISSUE THREAD

**Issue by abhigoku10** [ljanyst/ssd-tensorflow#13]
@ljanyst  HI i am new to tensorflow and ssd , thanks for the code , having few doubts 
When training for custom dataset should i download the Vgg_graph file ?
What is the use of training_data.py file ?
Thanks in advance

**Comment by ljanyst** [comment]
You just need to write your self a source definition file to train on an arbitrary dataset.
See: https://github.com/ljanyst/ssd-tensorflow/blob/master/source_pascal_voc.py
