### ISSUE TITLE
Training on VOC dataset 

### ISSUE THREAD

**Issue by abhigoku10** [ljanyst/ssd-tensorflow#14]
@ljanyst Hi i followed the steps in your readme file to train on voc dataset .

1. Ran process_dataset.py which gave a output of .pkl file in the pascal-voc folder 
2. Ran train.py which created  save_model.pb in the vgg_graph dir and vgg-graph.zip 
3.Ran detect.py to test the but its not giving any error or ouput

have followed the right steps can you pls elaborate on the procedure 
Thanks in advance

**Comment by ljanyst** [comment]
It really looks like you did not follow the steps. `train.py` produces a snapshot directory with a model that can be then used directly by `infer.py` to either produce a variety of statistics or annotated images. In order to use `detect.py`, you need to export the inference model first.
