### ISSUE TITLE
Error using train.py

### ISSUE THREAD

**Issue by abhigoku10** [ljanyst/ssd-tensorflow#15]
@ljanyst  HI when i train the pascal dataset i get this errro after 45% training 
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
[Finished in 10534.3s with exit code 1]
[shell_cmd: python -u "E:\sSD_tF\ssd-tensorflow-master\train.py"]
[dir: E:\sSD_tF\ssd-tensorflow-master]

i have not logged off /or disconnected my network pls help me out 
Thanks in advance

**Comment by ljanyst** [comment]
It looks like some Windows problem. I don't use Windows and I have never tried to run this software on Windows.
