### ISSUE TITLE
values of label_defs  in source_pascal_voc.py

### ISSUE THREAD

**Issue by kimna4** [ljanyst/ssd-tensorflow#16]
Hello,
Really thank you for sharing your source code.
I am trying to use your code with custom dataset.

How can I assign the values of "label_defs" in "source_pascal_voc.py" to my custom dataset classes?

Thank in advance.

**Comment by ljanyst** [comment]
The first value is the name of the class. The second one is the color you want the box of the label class to be. These are only used for drawing the final boxes, so choose whatever pleases you visually.

**Comment by kimna4** [comment]
I fully understand. Thank you so much. :)
