### ISSUE TITLE
urlopen error [Errno 110] Connection timed out>

### ISSUE THREAD

**Issue by gengkai258** [ljanyst/ssd-tensorflow#17]
helo, when i run train.py I always this erro :

urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

could you tell me how to solve it?thank you very much!

**Comment by ljanyst** [comment]
The training program needs to download the initial weights for the VGG network from Amazon. It's about 1GB worth of a zip file. There must be some sort of a problem with your network connection.
