### ISSUE TITLE
why did you use 1000x1000 image size?

### ISSUE THREAD

**Issue by airyym** [ljanyst/ssd-tensorflow#18]
I guess It is just to normalize anchor box and sample image as same dimension. Am I right?

**Comment by guillaume-guerdoux** [comment]
Hello, I used and studied this code and I'm pretty sure it's only to normalize images. You could have set it to 10x10 or 100x100

**Comment by airyym** [comment]
@guillaume-guerdoux thx! I got that point.

**Comment by ljanyst** [comment]
It's not exactly normalization. Some of the code needs box coordinates in pixels (ie. non-maximum suppression) while most of the code uses percentages of image size. There are places where I convert one coordinate system to the other. The image size does not matter as long as it's a square.

**Comment by airyym** [comment]
@ljanyst I understood. Thx!
