### ISSUE TITLE
why the sacle was not change in compute the anchors?

### ISSUE THREAD

**Issue by jackson2213** [ljanyst/ssd-tensorflow#22]
First thanks you project ,it help me a lot.
when i read you code to compute the anchor,i find the  's = map_params.scale'  ,but when compute the anchors,  s=0.9  wasn't any change.  i think the code should add 's=preset.maps[k].scale'

 please tell why? thank you!

    #---------------------------------------------------------------------------
    # Compute the actual boxes for every scale and feature map
    #---------------------------------------------------------------------------
    anchors = []
    for k in range(len(preset.maps)):
        fk = preset.maps[k].size[0]
        # **s=preset.maps[k].scale**
        for size in box_sizes[k]:
            for j in range(fk):
                y = (j+0.5)/float(fk)
                for i in range(fk):
                    x = (i+0.5)/float(fk)
                    box = Anchor(Point(x, y), Size(size[0], size[1]),
                                 i, j, s, k)
                    anchors.append(box)`

**Comment by ljanyst** [comment]
You're right, but it does not matter. This is just an artefact of the previous implementation. It's not used anywhere. I should really remove it to keep the code clean and avoid confusion.

**Comment by jackson2213** [comment]
Thank you for your answer !
