### ISSUE TITLE
 ./export_model.py error

### ISSUE THREAD

**Issue by RoseLii** [ljanyst/ssd-tensorflow#26]
Please help me, when I run ./export_model.py
usage: export_model.py [-h] [--metagraph-file METAGRAPH_FILE]
                       [--checkpoint-file CHECKPOINT_FILE]
                       [--output-file OUTPUT_FILE] --output-tensors
                       OUTPUT_TENSORS [OUTPUT_TENSORS ...]
export_model.py: error: the following arguments are required: --output-tensors
But when I run ./infer.py, test-output doesn't show anything。
when i run ./infer.py:
[i] Creating the model...
[i] Processing samples: 100%|██████████████████████████████████████████████████████████| 155/155 [00:54<00:00,  2.82batches/s]
[i] All done.
who can  guide me? The specific training detection process, how to do your own data set. I will be very grateful.

**Comment by ljanyst** [comment]
This tool is generic - you need to provide the names of the output tensors to work. Loot in the previous tickets - I believe it's `output/output` for this case.

**Comment by nymaferdous** [comment]
In infer.py, data_source is none. When I run, I see the number of files is 0. Please help.
