### ISSUE TITLE
Confidence loss is NaN?

### ISSUE THREAD

**Issue by sigmoidx** [ljanyst/ssd-tensorflow#27]
Hi,

It returns an error:

'Train 1/200: 19%'
'Confidence loss is NaN'

And 

'...tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: filter_summaries/conv1_1'

Any helps?

**Comment by dextroza** [comment]
+1

**Comment by ljanyst** [comment]
Lower the learning rate and retry.
