### ISSUE TITLE
personally  problem  of  understanding the code 

### ISSUE THREAD

**Issue by ghost** [ljanyst/ssd-tensorflow#29]
Hi, @ljanyst  
I'm learning your code,thank you for you perfect job.
the code of line 337  in ssdvgg.py :
X = l2_normalization (self.vgg_conv4_3, 20, 512,'l2_norm_conv4_3')
why to  set initial_scale  20 ?

**Comment by ljanyst** [comment]
That's what the paper recommends as the initial value - not that this is trainable.
