### ISSUE TITLE
Possible issue with Momentum Optimizer: Training is ~18x slower.

### ISSUE THREAD

**Issue by D-R-Williams** [ljanyst/ssd-tensorflow#30]
I was using the version with the Adam Optimizer for the longest time and finally tried out the latest version with Momentum. The batch times were usually around 1 second with the vgg300 preset and about 1.9 with vgg512 with the Adam version. I'm not sure what's causing this but training takes insanely long now (18.61s/batches). 

I find it odd that its says "ran out of memory trying to allocate 3.92GiB" when it says I have 6.60GiB free on my GPU. I tried updating tensorflow-gpu to the latest version but I didn't fix the problem.

I'm on windows 10, CUDA 9 installed, using these parameters:
python train.py --name "model" --vgg-dir "path\to\dataset" --num-workers 0"

Am I missing something obvious?

These are some of the warning messages I get while training:

> 2018-06-16 10:39:03.483635: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> 
> 2018-06-16 10:39:03.826152: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1356] Found device 0 with properties:
> name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.898
> pciBusID: 0000:01:00.0
> totalMemory: 8.00GiB freeMemory: 6.60GiB
> 
> 2018-06-16 10:39:03.830427: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1435] Adding visible gpu devices: 0
> 
> 2018-06-16 10:39:05.106763: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
> 
> 2018-06-16 10:39:05.108598: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:929]      0
> 
> 2018-06-16 10:39:05.109745: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:942] 0:   N
> 
> 2018-06-16 10:39:05.111337: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6379 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
> 
> [i] Creating the model...
> 
> 2018-06-16 10:39:13.629301: W T:\src\github\tensorflow\tensorflow\core\graph\graph_constructor.cc:1244] Importing a graph with a lower producer version 21 into an existing graph with producer version 26. Shape inference will have run different parts of the graph with different producer versions.
> [i] Training...
> 
> [i] Train  1/200:   0%|                                                                   | 0/263 [00:00<?, ?batches/s]
> 
> 2018-06-16 10:40:01.832411: W T:\src\github\tensorflow\tensorflow\core\common_runtime\bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.92GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
> 
> [i] Train  1/200:   2%|8                                                        | 4/263 [01:13<1:20:20, 18.61s/batches]

**Comment by ljanyst** [comment]
Well, you seem to have not enough GPU memory. I have only tried running it on fairly powerful GPU with > 10GB memory and did not notice any problems. Another thing may be using Windows. What I gather from a variety of posts and bug reports all over the place, TF has been primarily developed for Linux. Windows support seems to have bee retrofitted as an afterthought and many things still don't work.

**Comment by D-R-Williams** [comment]
Thanks for the quick reply. I get that message about memory with vgg512, which is what this log was from. With the old optimizer, I would get the same message for vgg512, but it would state it failed to allocate 6.6GB, which is the amount of free memory for my GPU. I noticed that the batch times are the same for BOTH vgg300 and vgg512; about 18.6 seconds. With Adam, vgg512 would take 1.9x longer. You could be right about the Windows support. I will just revert back to the original optimizer since that was working well enough. By the way, this project is amazing. Great work!
