### ISSUE TITLE
mod_conv6/filter doesn't exist in graph

### ISSUE THREAD

**Issue by vaishnavm217** [ljanyst/ssd-tensorflow#31]
Hi,
I modified you SSD net to implement one of the face detection papers. The `mod_conv6` and `mod_conv7` are not present in the graph. The function `__build_vgg_mods` is executing, but the layers are not getting added to the graph. Even the later layers are getting added (i.e conv8_1 etc)
**NOTE**
- my system supports tensorflow-1.4.1 due to cuda 8, I made the necessary changes.
- The fc layers (to which the weight is assigned ) is in the graph. Should I use that?

**Comment by vaishnavm217** [comment]
For now I have skipped it with error handling

**Comment by ljanyst** [comment]
Things work fine for me, so it must be due to the changes you've made.

**Comment by piyushkansalongit** [comment]
@ljanyst I suppose this is a valid issue. You must have used atrous convolution in which proper variables mod_conv6/filter:0 and mod_conv6/biases:0 has been defined but in case one sets this flag to False, then those variables are not defined by the expected names.
