### ISSUE TITLE
problem occurs during the train.py

### ISSUE THREAD

**Issue by franklu323** [ljanyst/ssd-tensorflow#32]
Hi, I followed the introduction and when I run the train.py, it just stopped during create the model, and showed the ‘connetctionreseterror [winerror:10054] An existing connection was forcibly closed by the remote host’.
![1](https://user-images.githubusercontent.com/28680833/42446912-1ad46184-83cc-11e8-8ff8-906f3450df15.JPG)
Can someone help me to solve this problem please. @ljanyst

**Comment by ljanyst** [comment]
Apparently your connection was reset when downloading the base model. This apparently happens on Windows a lot. My advice would be to stop using Windows for these things, it's more trouble than it's worth.
