### ISSUE TITLE
AttributeError: Can't pickle local object 'TrainingData.__batch_generator.<locals>.batch_producer'

### ISSUE THREAD

**Issue by Narasappapraveen** [ljanyst/ssd-tensorflow#35]
Hi, I am getting following error. When i debugged I found that error is coming at "w.start()" in training_data.py. Please let me know what went wrong.
Full error:

AttributeError: **Can't pickle local object 'TrainingData.__batch_generator.<locals>.batch_producer'**
> d:\tsr\ssd-tensorflow-master\training_data.py(175)gen_batch()
-> w.start()
(Pdb) C:\Users\VNP2KOR\AppData\Local\conda\conda\envs\tf_gpu\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\VNP2KOR\AppData\Local\conda\conda\envs\tf_gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\VNP2KOR\AppData\Local\conda\conda\envs\tf_gpu\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
**EOFError: Ran out of input**

**Comment by ljanyst** [comment]
This is a python3 project and it does not work on Windows (at least not in the multithreaded mode).

**Comment by huihuixiaohuihui** [comment]
how i deal with it
