### ISSUE TITLE
 ./detect.py

### ISSUE THREAD

**Issue by fusimeng** [ljanyst/ssd-tensorflow#37]
Traceback (most recent call last):
  File "./detect.py", line 125, in <module>
    main()
  File "./detect.py", line 100, in main
    img = cv2.resize(img, (300, 300))
cv2.error: OpenCV(4.0.0-pre) /home/opencv/opencv/modules/imgproc/src/resize.cpp:3784: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by ljanyst** [comment]
You need to download the dataset files.

**Comment by how2** [comment]
Professional code, thanks your great work. 
To this issue, I think at line 94, `files = sys.argv[1:]` should use `files = args.files` instead. Since if you only use image filename as input args, nothing wrong. But if use some other args like --model, the args will be filenames not found by opencv.
