### ISSUE TITLE
AttributeError: 'list' object has no attribute 'label'

### ISSUE THREAD

**Issue by zhangy52** [ljanyst/ssd-tensorflow#38]
First of all, thank you for making this available on Github. 
I'm fairly new to Machine Learning, and after a month or so of self study and work, I'm beat on this issue. 
When I run training.py, it gives me this error, 

Traceback (most recent call last):
  File "training.py", line 464, in <module>
    sys.exit(main())
  File "training.py", line 433, in main
    APs = training_ap_calc.compute_aps()
  File "average_precision.py", line 78, in compute_aps
    counts[box.label] += 1
AttributeError: 'list' object has no attribute 'label'

Thanks!

**Comment by ljanyst** [comment]
You probably use python2. This is a python3 program.
