### ISSUE TITLE
A problem about save .pb

### ISSUE THREAD

**Issue by Drsea123** [ljanyst/ssd-tensorflow#42]
when we export the model to an inference optimize graph run (use result/result as the name of the output tensor) in . /export_model.py.We find a question as :
Traceback (most recent call last):
  File "E:/defPerson-ssd-tf/export_model.py", line 42, in <module>
    help='names of the output tensors')
  File "D:\Anaconda\envs\py3.5\lib\argparse.py", line 1342, in add_argumen
    raise ValueError("length of metavar tuple does not match nargs")
ValueError: length of metavar tuple does not match nargs

what happend we want to find,please!

**Comment by ljanyst** [comment]
No idea. Looks like a Windows problem.
