### ISSUE TITLE
How to evaluate and calculate mAP on VOC test 2007 by infer.py

### ISSUE THREAD

**Issue by jamiechoi1995** [ljanyst/ssd-tensorflow#43]
Thanks for your great code to implement SSD, here are my questions:

how can I evaluate the model on VOC test 2007 and calculate mAP?

I can't compute the mAP as https://github.com/ljanyst/ssd-tensorflow/blob/e9c1ee5ccb90130c34cbc64bed62b6bc8b3880d2/infer.py#L147

and in https://github.com/ljanyst/ssd-tensorflow/blob/e9c1ee5ccb90130c34cbc64bed62b6bc8b3880d2/infer.py#L149, you use args.data_source, however, there no args.data_source in the parser part.

even if I add the args.data_source in parser, it shows:
`
Traceback (most recent call last):
  File "infer.py", line 286, in <module>
    sys.exit(main())
  File "infer.py", line 155, in main
    source.load_test_data(args.data_dir)
  File "/cephfs/group/teg-qboss-teg-qboss-ocr-shixi/jamiecai/workspace/detection/ssd-tensorflow-master_ljanyst/source_pascal_voc.py", line 196, in load_test_data
    annot = self.__build_annotation_list(root, 'test')
  File "/cephfs/group/teg-qboss-teg-qboss-ocr-shixi/jamiecai/workspace/detection/ssd-tensorflow-master_ljanyst/source_pascal_voc.py", line 81, in __build_annotation_list
    with open(root + '/ImageSets/Main/' + dataset_type + '.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pascal-voc/test/VOCdevkit/VOC2012/ImageSets/Main/test.txt'`

would you please update infer.py?
Thank you very much :D

**Comment by chenweizhi** [comment]
> Thanks for your great code to implement SSD, here are my questions:
> 
> how can I evaluate the model on VOC test 2007 and calculate mAP?
> 
> I can't compute the mAP as
> 
> [ssd-tensorflow/infer.py](https://github.com/ljanyst/ssd-tensorflow/blob/e9c1ee5ccb90130c34cbc64bed62b6bc8b3880d2/infer.py#L147)
> 
> Line 147 in [e9c1ee5](/ljanyst/ssd-tensorflow/commit/e9c1ee5ccb90130c34cbc64bed62b6bc8b3880d2)
> 
>  compute_stats = False 
> and in
> 
> [ssd-tensorflow/infer.py](https://github.com/ljanyst/ssd-tensorflow/blob/e9c1ee5ccb90130c34cbc64bed62b6bc8b3880d2/infer.py#L149)
> 
> Line 149 in [e9c1ee5](/ljanyst/ssd-tensorflow/commit/e9c1ee5ccb90130c34cbc64bed62b6bc8b3880d2)
> 
>  if args.data_source: 
> , you use args.data_source, however, there no args.data_source in the parser part.
> even if I add the args.data_source in parser, it shows:
> ` Traceback (most recent call last): File "infer.py", line 286, in <module> sys.exit(main()) File "infer.py", line 155, in main source.load_test_data(args.data_dir) File "/cephfs/group/teg-qboss-teg-qboss-ocr-shixi/jamiecai/workspace/detection/ssd-tensorflow-master_ljanyst/source_pascal_voc.py", line 196, in load_test_data annot = self.__build_annotation_list(root, 'test') File "/cephfs/group/teg-qboss-teg-qboss-ocr-shixi/jamiecai/workspace/detection/ssd-tensorflow-master_ljanyst/source_pascal_voc.py", line 81, in __build_annotation_list with open(root + '/ImageSets/Main/' + dataset_type + '.txt') as f: FileNotFoundError: [Errno 2] No such file or directory: 'pascal-voc/test/VOCdevkit/VOC2012/ImageSets/Main/test.txt'`
> 
> would you please update infer.py?
> Thank you very much :D

take a look at souce_pascal_voc.py , go ahead to function 'load_test_data'
change voc2012 to voc2007 if you are testing that one

**Comment by jamiechoi1995** [comment]
@chenweizhi thanks, I find that and I have created a PR #44
