### ISSUE TITLE
[Q] How to use the model to test some images?

### ISSUE THREAD

**Issue by sudonto** [ljanyst/ssd-tensorflow#5]
As stated in the title, could you provide me steps to test the model after training is finished? So the output is a window with box(s) telling the predicted class. I am completely new to this area.

**Comment by ljanyst** [comment]
Have a look at `infer.py`, it has options to dump a text file with detections in VOC format. You can also call a function from python like this: https://github.com/ljanyst/ssd-tensorflow/blob/master/infer.py#L219

**Comment by ElegantLin** [comment]
Thanks for your high-quality code, which is easy to understand.

I still have one question. If I want to just predict without testing annotation. Can I do it?

Thanks.
