### ISSUE TITLE
Question regarding layers 

### ISSUE THREAD

**Issue by MN85** [ljanyst/ssd-tensorflow#50]
I was going through the ssdvgg.py file and I'm a little confused as to where the intialize vgg layers are defined. I just see layers listed (layers = ['conv1_1', ..) and then l2 loss for them but I dont see them defined anywhere. Thanks in advance!

**Comment by ljanyst** [comment]
They are defined in the tensorflow snapshot of the orignal VGG network. See the `__load_vgg` function.
