### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by HoiM** [ljanyst/ssd-tensorflow#8]
Hello! Thank you for your code. Currently I don't get access to GPU so I'm trying your code on my laptop. I encountered this problem. Do you have any idea on what the reason is? 

Thank you so much!

$./train.py 
[i] Project name:          test
[i] Data directory:        pascal-voc
[i] VGG directory:         vgg_graph
[i] # epochs:              10
[i] Batch size:            8
[i] Tensorboard directory: tb
[i] Checkpoint interval:   5
[i] Learning rate:         0.001
[i] Learning rate decay:   0.97
[i] Optimizer  epsilon:    0.1
[i] Weight decay:          0.0005
[i] Continue:              False
[i] Number of workers:     4
[i] Creating directory test...
[i] Starting at epoch:     1
[i] Configuring the training data...
[i] # training samples:    26411
[i] # validation samples:  677
[i] # classes:             20
[i] Image size:            Size(w=300, h=300)
[i] Creating the model...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

**Comment by ljanyst** [comment]
You've run out of memory.
